# Register new user
POST   http://localhost:3042/api/users/register  HTTP/1.1
Content-Type: application/json

{
  "name": "Джон",
  "email": "johndoe@somemail.com",
  "password": "testpass",
  "sex": "male",
  "birthDate": "2000-09-27 18:00:00.000",
  "role": "trainer",
  "description": "At tellus at urna condimentum. Odio morbi quis commodo odio aenean sed. Malesuada nunc vel risus commodo viverra.",
  "location": "Petrogradskaya",
  "trainingLevel": "professional",
  "trainingType": ["running", "box", "crossfit"],
  "merits": "Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ipsum dolor sit amet tristique sollicitudin. Amet nisl.",
  "isReadyForTraining": false
}
###

# Update user
POST   http://localhost:3042/api/users/update  HTTP/1.1
Content-Type: application/json

{
  "id": "9584ad02-ed85-438e-aead-797fd55978d7",
  "name": "Валерия"
}
###

# Register new user
POST   http://localhost:3042/api/users/test  HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"
johndoe@somemail.com

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
Джон

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"
"testpass"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="sex"
"male"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="role"
"trainer"

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Login
POST   http://localhost:3042/api/users/login  HTTP/1.1
Content-Type: application/json

{
  "email": "olga@somemail.com",
  "password": "testpass"
}

###

# Login
POST   http://localhost:3042/api/users/login  HTTP/1.1
Content-Type: application/json

{
  "email": "johndoe@somemail.com",
  "password": "testpass"
}

###

# Refresh tokens pair
POST   http://localhost:3042/api/users/refresh  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZThiOTQyNy1hNzVmLTRjNWEtYmQ1My1hMmVmOWEyN2YxZmEiLCJlbWFpbCI6ImpvaG5kb2VAc29tZW1haWwuY29tIiwibmFtZSI6ItCU0LbQvtC9Iiwicm9sZSI6InRyYWluZXIiLCJpYXQiOjE2OTkyNzY0MjUsImV4cCI6MTY5OTI3NjcyNX0.J7MmY84bXfI6C9lm51Gd9Jrfa3aVMeByNH_sABRUWe8

###

# Get user detail
GET   http://localhost:3042/api/users/detail/4acd9867-7fd3-4fd7-8c9b-3641bba475b6  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYmQwZWE1Zi03ZTVlLTQ1MmYtOGM3YS1kODNjMDBjYTU0NTEiLCJlbWFpbCI6Im9sZ2FAc29tZW1haWwuY29tIiwibmFtZSI6ItCe0LvRjNCz0LAiLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTI3NjI1MywiZXhwIjoxNjk5Mjc2NTUzfQ.5Ahn3aVxtgmlZZOoj7r5wWXwRZ-FM1yYmNgQrh-Dm8M

###

# Get users list
GET   http://localhost:3042/api/users/usersList?sortPriority=user  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYmQwZWE1Zi03ZTVlLTQ1MmYtOGM3YS1kODNjMDBjYTU0NTEiLCJlbWFpbCI6Im9sZ2FAc29tZW1haWwuY29tIiwibmFtZSI6ItCe0LvRjNCz0LAiLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTI5OTA4MywiZXhwIjoxNjk5Mjk5MzgzfQ.oowNAVwHPmAQl_gW0T0sd8jZalw95mBH9vEZCvzS9nw

###

# Get users list
GET   http://localhost:3042/api/users/usersList?location=Pionerskaya&trainingLevel=amateur&trainingType[0]=running&trainingType[1]=box  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYmQwZWE1Zi03ZTVlLTQ1MmYtOGM3YS1kODNjMDBjYTU0NTEiLCJlbWFpbCI6Im9sZ2FAc29tZW1haWwuY29tIiwibmFtZSI6ItCe0LvRjNCz0LAiLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTI5NzgxNSwiZXhwIjoxNjk5Mjk4MTE1fQ.EGkpx7drT6fmbvaFZUTizDR1tCHDwMaqYnXUR7IIYWk

###


#
######## TRAINER ACCOUNT ########
###

# TEST
GET   http://localhost:3042/api/trainerAccount/index  HTTP/1.1

###

# Send new training notifications
POST   http://localhost:3042/api/trainerAccount/sendNewTrainingNotifications  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZThiOTQyNy1hNzVmLTRjNWEtYmQ1My1hMmVmOWEyN2YxZmEiLCJlbWFpbCI6ImpvaG5kb2VAc29tZW1haWwuY29tIiwibmFtZSI6ItCU0LbQvtC9Iiwicm9sZSI6InRyYWluZXIiLCJpYXQiOjE2OTkyOTkzNTcsImV4cCI6MTY5OTI5OTY1N30.NMCT5EVtDNGVUkTPAnBeTXP6dSFSYD8Y5s_7wqCHYYg
Content-Type: application/json

{
  "trainingCreatorId": "7f1cfe6d-c684-436e-ab9d-c8308eb534df",
  "trainingId": "79bab13d-f236-4b5c-af2f-3207d5902fa2"
}

###

# Create new training
POST   http://localhost:3042/api/trainerAccount/createTraining  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ZjFjZmU2ZC1jNjg0LTQzNmUtYWI5ZC1jODMwOGViNTM0ZGYiLCJlbWFpbCI6ImpvaG5kb2VAc29tZW1haWwuY29tIiwibmFtZSI6ItCU0LbQvtC9Iiwicm9sZSI6InRyYWluZXIiLCJpYXQiOjE2OTk1NjI0MjksImV4cCI6MTY5OTU2MjcyOX0.eVZmMO60mqRYaIpKHUodb7SdbgvcekoSIZ-HCo7bjgs
Content-Type: application/json

{
  "name": "",
  "backgroundImgSrc": "",
  "trainingLevel": "professional",
  "trainingType": "box",
  "trainingDuration": "80-100",
  "price": 2042,
  "calories": 3042,
  "description": "",
  "sex": "male",
  "videoDemoSrc": "",
  "rating": 0,
  "trainingCreatorId": "7f1cfe6d-c684-436e-ab9d-c8308eb534df",
  "isSpecial": true
}

###

# Update exist training
POST   http://localhost:3042/api/trainerAccount/updateTraining  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ZjFjZmU2ZC1jNjg0LTQzNmUtYWI5ZC1jODMwOGViNTM0ZGYiLCJlbWFpbCI6ImpvaG5kb2VAc29tZW1haWwuY29tIiwibmFtZSI6ItCU0LbQvtC9Iiwicm9sZSI6InRyYWluZXIiLCJpYXQiOjE2OTk1NjI0MjksImV4cCI6MTY5OTU2MjcyOX0.eVZmMO60mqRYaIpKHUodb7SdbgvcekoSIZ-HCo7bjgs
Content-Type: application/json

{
  "id": "79bab13d-f236-4b5c-af2f-3207d5902fa2",
  "name": "Пархай как бабочка, жаль как пчела."
}

###

# Get training list
POST   http://localhost:3042/api/trainerAccount/getTrainingList?priceRange[0]=2000&priceRange[1]=3000&duration=50-80  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZThiOTQyNy1hNzVmLTRjNWEtYmQ1My1hMmVmOWEyN2YxZmEiLCJlbWFpbCI6ImpvaG5kb2VAc29tZW1haWwuY29tIiwibmFtZSI6ItCU0LbQvtC9Iiwicm9sZSI6InRyYWluZXIiLCJpYXQiOjE2OTkyOTkzNTcsImV4cCI6MTY5OTI5OTY1N30.NMCT5EVtDNGVUkTPAnBeTXP6dSFSYD8Y5s_7wqCHYYg
Content-Type: application/json

{
  "trainerId": "6c81306f-beb0-495d-a044-4fc6a2209724"
}

###

# Get training list
POST   http://localhost:3042/api/trainerAccount/getTrainingList?priceRange[0]=100&priceRange[1]=200&caloriesRange[0]=2500&caloriesRange[1]=4000&rate=4&duration=10-30  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZThiOTQyNy1hNzVmLTRjNWEtYmQ1My1hMmVmOWEyN2YxZmEiLCJlbWFpbCI6ImpvaG5kb2VAc29tZW1haWwuY29tIiwibmFtZSI6ItCU0LbQvtC9Iiwicm9sZSI6InRyYWluZXIiLCJpYXQiOjE2OTkyOTkzNTcsImV4cCI6MTY5OTI5OTY1N30.NMCT5EVtDNGVUkTPAnBeTXP6dSFSYD8Y5s_7wqCHYYg
Content-Type: application/json

{
  "trainerId": "6c81306f-beb0-495d-a044-4fc6a2209724"
}

###

# Get trainer purchases
POST   http://localhost:3042/api/trainerAccount/getPurchases  HTTP/1.1
Content-Type: application/json

{
  "trainerId": "6c81306f-beb0-495d-a044-4fc6a2209724"
}

###



#
######## USER ACCOUNT ########
###

# Get users's friends
GET   http://localhost:3042/api/userAccount/friends/2bd0ea5f-7e5e-452f-8c7a-d83c00ca5451  HTTP/1.1

###

# Add new friend
POST   http://localhost:3042/api/userAccount/friends  HTTP/1.1
Content-Type: application/json

{
  "userId": "2bd0ea5f-7e5e-452f-8c7a-d83c00ca5451",
  "newFriendId": "2bd0ea5f-7e5e-452f-8c7a-d83c00ca5447"
}

###

# Remove from friends list
DELETE    http://localhost:3042/api/userAccount/friends  HTTP/1.1
Content-Type: application/json

{
  "userId": "2bd0ea5f-7e5e-452f-8c7a-d83c00ca5451",
  "friendId": "2bd0ea5f-7e5e-452f-8c7a-d83c00ca5447"
}

###

# Remove from friends list
DELETE    http://localhost:3042/api/userAccount/friends  HTTP/1.1
Content-Type: application/json

{
  "userId": "2bd0ea5f-7e5e-452f-8c7a-d83c00ca5451",
  "friendId": "2bd0ea5f-7e5e-452f-8c7a-d83c00ca5447"
}

###

# Get users's balance
GET   http://localhost:3042/api/userAccount/balance/2bd0ea5f-7e5e-452f-8c7a-d83c00ca5451  HTTP/1.1

###

# Add to new trainings subscribers
POST    http://localhost:3042/api/userAccount/subscribe  HTTP/1.1
Content-Type: application/json

{
  "trainerId": "7f1cfe6d-c684-436e-ab9d-c8308eb534df",
  "newSubscriberId": "2bd0ea5f-7e5e-452f-8c7a-d83c00ca5449"
}

###

# Remove from new trainings subscribers
DELETE    http://localhost:3042/api/userAccount/unsubscribe  HTTP/1.1
Content-Type: application/json

{
  "trainerId": "7f1cfe6d-c684-436e-ab9d-c8308eb534df",
  "subscriberId": "2bd0ea5f-7e5e-452f-8c7a-d83c00ca5442"
}
