# GET REVIEWS
GET   http://localhost:3042/api/reviews/1fb236e2-019e-4c87-aa5c-5f7d230cb1bd  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYmQwZWE1Zi03ZTVlLTQ1MmYtOGM3YS1kODNjMDBjYTU0NTEiLCJlbWFpbCI6Im9sZ2FAc29tZW1haWwuY29tIiwibmFtZSI6ItCe0LvRjNCz0LAiLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTgyNDY0MywiZXhwIjoxNjk5ODYwNjQzfQ.5syFbMbN1ke89E-jfLhxl50CCucluVbl7ZnCaXbkXsk

###

# CREATE REVIEW
POST   http://localhost:3042/api/reviews  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYmQwZWE1Zi03ZTVlLTQ1MmYtOGM3YS1kODNjMDBjYTU0NTEiLCJlbWFpbCI6Im9sZ2FAc29tZW1haWwuY29tIiwibmFtZSI6ItCe0LvRjNCz0LAiLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTgyNDY0MywiZXhwIjoxNjk5ODYwNjQzfQ.5syFbMbN1ke89E-jfLhxl50CCucluVbl7ZnCaXbkXsk
Content-Type: application/json

{
  "trainingId": "1fb236e2-019e-4c87-aa5c-5f7d230cb1bd",
  "rating": 1,
  "text": "Отлично потренировались, всё бы ничего, но сломан нос и выбито два зуба. Руки бинтовать запретил. Перчатки выдал рваные. Не тренер, а м#!@к какой-то..."
}

###
