# GET TRAININGS CATALOGUE
GET   http://localhost:3042/api/trainings/catalogue?sortDirection=desc  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYmQwZWE1Zi03ZTVlLTQ1MmYtOGM3YS1kODNjMDBjYTU0NTEiLCJlbWFpbCI6Im9sZ2FAc29tZW1haWwuY29tIiwibmFtZSI6ItCe0LvRjNCz0LAiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwMTY5MTE5MiwiZXhwIjoxNzAxNzI3MTkyfQ.BeF4KZbVVNVKUcjjyM3yT8K9xav9MZ5mFI5ER6qabe8

###

# GET TRAININGS CATALOGUE (WITH QUERY PARAMS)
GET   http://localhost:3042/api/trainings/catalogue?priceRange[0]=100&priceRange[1]=5000&caloriesRange[0]=0&caloriesRange[1]=5000&trainingType=yoga  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NTg0YWQwMi1lZDg1LTQzOGUtYWVhZC03OTdmZDU1OTc4ZDgiLCJlbWFpbCI6InRyYWluaGFyZHdpdGh2YWxlcnlAc29tZW1haWwuY29tIiwibmFtZSI6ItCS0LDQu9C10YDQuNGPIiwicm9sZSI6InRyYWluZXIiLCJpYXQiOjE2OTk4MTYyOTEsImV4cCI6MTY5OTg1MjI5MX0.I1jYCS3Ut9ILGOXYmWXXRXivvcH72Sqor4pXED2YKMw

###
