# GET TRAININGS CATALOGUE
GET   http://localhost:3042/api/trainings/catalogue?sortDirection=desc  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYmQwZWE1Zi03ZTVlLTQ1MmYtOGM3YS1kODNjMDBjYTU0NTEiLCJlbWFpbCI6Im9sZ2FAc29tZW1haWwuY29tIiwibmFtZSI6ItCe0LvRjNCz0LAiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwMjAzNjA3NiwiZXhwIjoxNzAyMDcyMDc2fQ.yS6NCj0IMZ5RoB43_2WxTumQj7H8uYIHDyIlxUF-Q2s

###

# GET TRAININGS CATALOGUE (WITH QUERY PARAMS)
GET   http://localhost:3042/api/trainings/catalogue?priceRange[0]=100&priceRange[1]=5000&caloriesRange[0]=0&caloriesRange[1]=5000&trainingType=yoga  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NTg0YWQwMi1lZDg1LTQzOGUtYWVhZC03OTdmZDU1OTc4ZDgiLCJlbWFpbCI6InRyYWluaGFyZHdpdGh2YWxlcnlAc29tZW1haWwuY29tIiwibmFtZSI6ItCS0LDQu9C10YDQuNGPIiwicm9sZSI6InRyYWluZXIiLCJpYXQiOjE2OTk4MTYyOTEsImV4cCI6MTY5OTg1MjI5MX0.I1jYCS3Ut9ILGOXYmWXXRXivvcH72Sqor4pXED2YKMw

###

# GET TRAININGS CATALOGUE
POST    http://localhost:3042/api/trainings/detail  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYmQwZWE1Zi03ZTVlLTQ1MmYtOGM3YS1kODNjMDBjYTU0NTEiLCJlbWFpbCI6Im9sZ2FAc29tZW1haWwuY29tIiwibmFtZSI6ItCe0LvRjNCz0LAiLCJyb2xlIjoidXNlciIsImlhdCI6MTcwMjAzNjA3NiwiZXhwIjoxNzAyMDcyMDc2fQ.yS6NCj0IMZ5RoB43_2WxTumQj7H8uYIHDyIlxUF-Q2s
Content-Type: application/json

{
  "id": "af430d39-5608-4815-9de9-ff43be0c6936"
}
###
