export enum AppRoutes {
  SIGN_IN = '/signIn',
  SIGN_UP = '/signUp',
  INDEX = '/userAccount/index',
  TRAINER_ACCOUNT = '/trainerAccount',
  QUESTIONNAIRE_COACH = '/questionnaireCoach',
  QUESTIONNAIRE_USER = '/questionnaireUser',
  NOT_FOUND = '/notFound',
  BAD_REQUEST = '/badRequest',
  TRAINING_CARD_USER = '/userAccount/trainingCard/:id',
  TRAINING_CARD_TRAINER = '/trainerAccount/trainingCard/:id',
  TRAINING_CATALOG = '/trainingCatalog',
  USERS_CATALOG = '/userAccount/usersCatalog',
  USER_CARD = '/userAccount/userCard',
  TRAINER_CARD = '/userAccount/trainerCard',
  FRIEND_LIST_USER = '/userAccount/friendsList',
  FRIEND_LIST_TRAINER = '/trainerAccount/friendsList',
}
